language: python
cache: pip
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  make ci
after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls; fi
