api:
  url: https://api.transilien.com/gare/${departure_station}/depart/${arrival_station}
  departure_station: 00000000
  arrival_station: 00000000
  user: user
  password: password

refresh_time:
  default: 10
  step: 10
  max: 30

device:
  type: console
